apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: install-openshift-pipelines-operator
  namespace: acm-default-fleet-policies
  labels:
    app.kubernetes.io/part-of: openshift-quickstarts
    app.kubernetes.io/managed-by: openshift-quickstarts
    app.kubernetes.io/component: rhacm-policies
    rhacm-policies/scope: fleet
  annotations:
    policy.open-cluster-management.io/description: install-openshift-pipelines-operator
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/controls: CM Baseline Configuration
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-openshift-pipelines-operator
        spec:
          remediationAction: enforce
          severity: high
          complianceType: musthave
          subscription:
            name: openshift-pipelines-operator-rh
            namespace: openshift-operators
            channel: latest
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          upgradeApproval: Automatic
          versions: []
          # No operatorGroup needed: openshift-operators already has an
          # AllNamespaces OperatorGroup created by OLM at cluster bootstrap.
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: install-openshift-pipelines-operator-placement
  namespace: acm-default-fleet-policies
  labels:
    app.kubernetes.io/part-of: openshift-quickstarts
    app.kubernetes.io/managed-by: openshift-quickstarts
    app.kubernetes.io/component: rhacm-policies
spec:
  tolerations: []
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: vendor
              operator: In
              values:
                - OpenShift
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: install-openshift-pipelines-operator-placement
  namespace: acm-default-fleet-policies
  labels:
    app.kubernetes.io/part-of: openshift-quickstarts
    app.kubernetes.io/managed-by: openshift-quickstarts
    app.kubernetes.io/component: rhacm-policies
placementRef:
  name: install-openshift-pipelines-operator-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: install-openshift-pipelines-operator
    apiGroup: policy.open-cluster-management.io
    kind: Policy
