# Multi-architecture support
ARG BUILDPLATFORM
ARG TARGETPLATFORM
FROM fedora:44

# Set architecture variables for binary downloads
# If TARGETPLATFORM is not set, auto-detect from runtime
RUN if [ -n "$TARGETPLATFORM" ]; then \
        PLATFORM="$TARGETPLATFORM"; \
    else \
        case "$(uname -m)" in \
            "x86_64") PLATFORM="linux/amd64" ;; \
            "aarch64") PLATFORM="linux/arm64" ;; \
            *) echo "Unsupported architecture: $(uname -m)" && exit 1 ;; \
        esac; \
    fi && \
    case "$PLATFORM" in \
        "linux/amd64") \
            echo "amd64" > /tmp/arch && \
            echo "x86_64" > /tmp/arch_alt && \
            echo "Linux-64bit" > /tmp/arch_rpm && \
            echo "x86_64" > /tmp/arch_rosa ;; \
        "linux/arm64") \
            echo "arm64" > /tmp/arch && \
            echo "aarch64" > /tmp/arch_alt && \
            echo "Linux-ARM64" > /tmp/arch_rpm && \
            echo "arm64" > /tmp/arch_rosa ;; \
        *) \
            echo "Unsupported platform: $PLATFORM" && exit 1 ;; \
    esac

# Install necessary packages
RUN dnf install -y \
    bash \
    bash-completion \
    curl \
    wget \
    git \
    tree \
    less \
    more \
    tar \
    zip \
    unzip \
    jq \
    rsync \
    which \
    vim \
    vim-enhanced \
    iputils \
    bind-utils \
    httpd-tools \
    iproute \
    traceroute \
    procps-ng \
    util-linux-core \
    wireshark \
    htop \
    net-tools \
    telnet \
    tcpdump \
    nmap \
    mtr \
    strace \
    lsof \
    iftop \
    iperf \
    iperf3 \
    tmux \
    screen \
    nano \
    zip \
    unzip \
    nc \
    python3 \
    python3-pip \
    python3-passlib \
    make \
    gcc \
    gdb \
    openssl \
    openssh-clients \
    sudo \
    sshpass \
    ansible-core \
    ansible \
    skopeo \
    buildah \
    podman && \
    dnf clean all

# Install Ansible collections used by playbooks
COPY files/ansible-requirements.yml /tmp/ansible-requirements.yml
RUN ansible-galaxy collection install -r /tmp/ansible-requirements.yml && \
    rm -f /tmp/ansible-requirements.yml

# Download/Install OpenShift and Kubernetes Client binaries
RUN ARCH_ALT=$(cat /tmp/arch_alt) && \
    wget -q -O oc.tar.gz "https://mirror.openshift.com/pub/openshift-v4/${ARCH_ALT}/clients/ocp/stable/openshift-client-linux.tar.gz" && \
    tar -xzf oc.tar.gz && \
    install -m 755 oc /usr/local/bin/oc  && \
    install -m 755 kubectl /usr/local/bin/kubectl && \
    oc completion bash > /etc/bash_completion.d/oc && \
    kubectl completion bash > /etc/bash_completion.d/kubectl && \
    rm -rf oc.tar.gz oc kubectl README.md

# Download/Install virtctl binaries
RUN ARCH=$(cat /tmp/arch) && \
    VERSION=v1.8.2 && \
    wget -q -O virtctl "https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/virtctl-${VERSION}-linux-${ARCH}" && \
    install -m 755 virtctl /usr/local/bin/virtctl && \
    virtctl completion bash > /etc/bash_completion.d/virtctl && \
    rm -rf virtctl

# Download/Install flightctl binaries
RUN wget -q -O flightctl "https://github.com/flightctl/flightctl/releases/download/v1.1.2/flightctl-darwin-amd64.zip" && \
    install -m 755 flightctl /usr/local/bin/flightctl && \
    # flightctl completion bash > /etc/bash_completion.d/flightctl && \
    rm -rf flightctl

# Download/Install Kustomize Client binary
RUN ARCH=$(cat /tmp/arch) && \
    wget -q -O kustomize.tar.gz "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.8.1/kustomize_v5.8.1_linux_${ARCH}.tar.gz" && \
    tar -xzf kustomize.tar.gz && \
    install -m 755 kustomize /usr/local/bin/kustomize && \
    kustomize completion bash > /etc/bash_completion.d/kustomize && \
    rm -rf kustomize.tar.gz kustomize

# Download/Install Helm Client binary
RUN ARCH=$(cat /tmp/arch) && \
    wget -q -O helm.tar.gz "https://get.helm.sh/helm-v4.2.0-linux-${ARCH}.tar.gz" && \
    tar -xzf helm.tar.gz && \
    install -m 755 "linux-${ARCH}/helm" /usr/local/bin/helm && \
    helm completion bash > /etc/bash_completion.d/helm && \
    rm -rf helm.tar.gz "linux-${ARCH}"

# Download/Install Tekton CLI RPM directly from URL
RUN ARCH_RPM=$(cat /tmp/arch_rpm) && \
    dnf install -y "https://github.com/tektoncd/cli/releases/download/v0.45.0/tektoncd-cli-0.45.0_${ARCH_RPM}.rpm" && \
    dnf clean all && \
    tkn completion bash > /etc/bash_completion.d/tkn

# Download/Install roxctl from URL
RUN ARCH=$(cat /tmp/arch) && \
    case "$ARCH" in \
        "amd64") \
            curl -L -f -o roxctl "https://mirror.openshift.com/pub/rhacs/assets/latest/bin/linux/roxctl" ;; \
        "arm64") \
            curl -L -f -o roxctl "https://mirror.openshift.com/pub/rhacs/assets/latest/bin/linux/roxctl-arm64" ;; \
        *) \
            echo "Unsupported architecture for roxctl: $ARCH" && exit 1 ;; \
    esac && \
    install -m 755 roxctl /usr/local/bin/roxctl && \
    roxctl completion bash > /etc/bash_completion.d/roxctl && \
    rm -rf roxctl

# Download/Install AWS CLI from URL
RUN ARCH_ALT=$(cat /tmp/arch_alt) && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-${ARCH_ALT}.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf awscliv2.zip aws

# Download/Install Azure CLI from URL
RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc && \
    dnf install -y https://packages.microsoft.com/config/fedora/44/packages-microsoft-prod.rpm && \
    dnf install -y azure-cli && \
    dnf clean all

# Download/Install OpenShift Installer
RUN ARCH_ALT=$(cat /tmp/arch_alt) && \
    wget -q -O openshift-install-linux.tar.gz "https://mirror.openshift.com/pub/openshift-v4/${ARCH_ALT}/clients/ocp/stable/openshift-install-linux.tar.gz" && \
    tar -xzf openshift-install-linux.tar.gz && \
    install -m 755 openshift-install /usr/local/bin/openshift-install && \
    openshift-install completion bash > /etc/bash_completion.d/openshift-install && \
    rm -rf openshift-install-linux.tar.gz openshift-install

# Download/Install Rosa CLI
RUN ARCH_ROSA=$(cat /tmp/arch_rosa) && \
    wget -q -O rosa.tar.gz "https://github.com/openshift/rosa/releases/download/v1.2.63/rosa_Linux_${ARCH_ROSA}.tar.gz" && \
    tar -xzf rosa.tar.gz && \
    install -m 755 rosa /usr/local/bin/rosa && \
    rosa completion bash > /etc/bash_completion.d/rosa && \
    rm -rf rosa.tar.gz rosa

# Download Knative CLI
RUN ARCH=$(cat /tmp/arch) && \
    curl -L -f -o kn "https://github.com/knative/client/releases/download/knative-v1.22.0/kn-linux-${ARCH}" && \
    install -m 755 kn /usr/local/bin/kn && \
    rm -rf kn

# Download Subctl CLI
RUN ARCH=$(cat /tmp/arch) && \
    curl -L -f -o subctl.tar.xz "https://developers.redhat.com/content-gateway/file/pub/rhacm/clients/subctl/0.20.1-2/subctl-0.20.1-2-linux-${ARCH}.tar.xz" && \
    tar -xJf subctl.tar.xz && \
    install -m 755 subctl-v0.20.1/subctl-v0.20.1-linux-${ARCH} /usr/local/bin/subctl && \
    rm -rf subctl.tar.xz subctl-v0.20.1
