apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# List every manifest that makes up this application.
# resources:
#   - namespace.yaml
#   - deployment.yaml
#   - service.yaml
#   - route.yaml
