apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hello-openshift
  namespace: hello-openshift
  labels:
    app.kubernetes.io/name: hello-openshift
    app.kubernetes.io/part-of: openshift-quickstarts
spec:
  source:
    type: Git
    git:
      uri: https://github.com/Caseraw/OpenShiftQuickStarts.git
      ref: main
    contextDir: applications/hello-openshift/src
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: hello-openshift:latest
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  runPolicy: Serial
