apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
  labels:
    app.kubernetes.io/part-of: openshift-quickstarts
    app.kubernetes.io/managed-by: openshift-quickstarts
    app.kubernetes.io/component: rhacm
spec: {}
