apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management
  labels:
    app.kubernetes.io/part-of: openshift-quickstarts
    app.kubernetes.io/managed-by: openshift-quickstarts
    app.kubernetes.io/component: rhacm
  annotations:
    openshift.io/display-name: "Red Hat Advanced Cluster Management"
    openshift.io/description: >-
      Namespace for the Red Hat Advanced Cluster Management for Kubernetes operator
      and the MultiClusterHub instance.
