apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: open-cluster-management
  namespace: open-cluster-management
  labels:
    app.kubernetes.io/part-of: openshift-quickstarts
    app.kubernetes.io/managed-by: openshift-quickstarts
    app.kubernetes.io/component: rhacm
spec:
  targetNamespaces:
    - open-cluster-management
